export const topics = [
  { id: 0, title: "Problems on Train", url: "https://www.indiabix.com/aptitude/problems-on-trains/" },
  { id: 1, title: "Height and Distance", url: "https://www.indiabix.com/aptitude/height-and-distance/" },
  { id: 2, title: "Simple Interest", url: "https://www.indiabix.com/aptitude/simple-interest/" },
  { id: 3, title: "Profit and Loss", url: "https://www.indiabix.com/aptitude/profit-and-loss/" },
  { id: 4, title: "Percentage", url: "https://www.indiabix.com/aptitude/percentage/" },
  { id: 5, title: "Calendar", url: "https://www.indiabix.com/aptitude/calendar/" },
  { id: 6, title: "Average", url: "https://www.indiabix.com/aptitude/average/" },
  { id: 7, title: "Volume and Surface Area", url: "https://www.indiabix.com/aptitude/volume-and-surface-area/" },
  { id: 8, title: "Numbers", url: "https://www.indiabix.com/aptitude/numbers/" },
  { id: 9, title: "Problems on HCF and LCM", url: "https://www.indiabix.com/aptitude/problems-on-hcf-and-lcm/" },
  { id: 10, title: "Simplification", url: "https://www.indiabix.com/aptitude/simplification/" },
  { id: 11, title: "Surds and Indices", url: "https://www.indiabix.com/aptitude/surds-and-indices/" },
  { id: 12, title: "Chain Rule", url: "https://www.indiabix.com/aptitude/chain-rule/" },
  { id: 13, title: "Boats and Streams", url: "https://www.indiabix.com/aptitude/boats-and-streams/" },
  { id: 14, title: "Logarithm", url: "https://www.indiabix.com/aptitude/logarithm/" },
  { id: 15, title: "Stocks and Shares", url: "https://www.indiabix.com/aptitude/stocks-and-shares/" },
  { id: 16, title: "True Discount", url: "https://www.indiabix.com/aptitude/true-discount/" },
  { id: 17, title: "Odd Man Out and Series", url: "https://www.indiabix.com/aptitude/odd-man-out-and-series/" },
  { id: 18, title: "Time and Distance", url: "https://www.indiabix.com/aptitude/time-and-distance/" },
  { id: 19, title: "Time and Work", url: "https://www.indiabix.com/aptitude/time-and-work/" },
  { id: 20, title: "Compound Interest", url: "https://www.indiabix.com/aptitude/compound-interest/" },
  { id: 21, title: "Partnership", url: "https://www.indiabix.com/aptitude/partnership/" },
  { id: 22, title: "Problems on Ages", url: "https://www.indiabix.com/aptitude/problems-on-ages/" },
  { id: 23, title: "Clock", url: "https://www.indiabix.com/aptitude/clock/" },
  { id: 24, title: "Area", url: "https://www.indiabix.com/aptitude/area/" },
  { id: 25, title: "Permutation and Combination", url: "https://www.indiabix.com/aptitude/Permuatation-and-combination/" },
  { id: 26, title: "Problem on Numbers", url: "https://www.indiabix.com/aptitude/problems-on-numbers/" },
  { id: 27, title: "Decimal Fraction", url: "https://www.indiabix.com/aptitude/decimal-fraction/" },
  { id: 28, title: "Square Root and Cube Root", url: "https://www.indiabix.com/aptitude/square-root-and-cube-root/" },
  { id: 29, title: "Ratio and Proportion", url: "https://www.indiabix.com/aptitude/ratio-and-proportion/" },
  { id: 30, title: "Pipes and Cistern", url: "https://www.indiabix.com/aptitude/pipes-and-cistern/" },
  { id: 31, title: "Allegation or Mixture", url: "https://www.indiabix.com/aptitude/alligation-or-mixture/" },
  { id: 32, title: "Races and Games", url: "https://www.indiabix.com/aptitude/races-and-games/" },
  { id: 33, title: "Probability", url: "https://www.indiabix.com/aptitude/probability/" },
  { id: 34, title: "Banker's Discount", url: "https://www.indiabix.com/aptitude/bankers-discount/" },
];